# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:17.0.2
    working_directory: ~/build-workdir
    steps:
      - checkout
      - run:
          name: Build and tests (unit + integration)
          command: mvn clean verify
      - run:
          name: Code analysis on SonarCloud
          command: mvn -DskipTests sonar:sonar

  build-and-publish-docker-image:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run:
          name: Build and publish Docker image (main branch only)
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              mvn clean compile jib:build -Pci -Djib.to.auth.username=$DOCKER_HUB_USERNAME -Djib.to.auth.password=$DOCKER_HUB_PASSWORD
            else
              echo "Skipping Docker build and publish - not on main branch"
            fi

orbs:
  jira: circleci/jira@1.3.1

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  build:
    jobs:
      - build-and-test:
          context: SonarCloud
          post-steps:
            - jira/notify
      - build-and-publish-docker-image:
          requires:
            - build-and-test
